[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
name = "assets"
version = "0.1.0"

[dependencies]
failure = "0.1.3"
image = "0.20.1"
serde = "1.0.82"
serde_cbor = "0.9.0"
serde_derive = "1.0.82"
serde_yaml = "0.8.8"
tar = "0.4.20"
zstd = "0.4.21+zstd.1.3.7"
