[workspace]
members = [
	"bins/ia",
	"bins/ia-asset-tool",
	"bins/ia-internal-debug-tool",
	"bins/ia-model-viewer",
	"libs/assets",
	"libs/ecstasy",
	"libs/ecstasy_proc_macros",
	"libs/iqm",
	"libs/renderer",
]
