[package]
name = "engine"
version = "0.1.0"
authors = ["Nathan Ringo <remexre@gmail.com>"]

[dependencies]
failure = "0.1.3"
# frunk = "0.2.3"
frunk = { "git" = "https://github.com/remexre/frunk.git", "branch" = "hmappable_fnmut" }
log = "0.4.6"
rayon = "1.0.3"
