[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[dependencies]
failure = "0.1.3"
# frunk = "0.2.3"
frunk = { "git" = "https://github.com/remexre/frunk.git", "branch" = "funcmut_polymut" }
log = "0.4.6"
rayon = "1.0.3"
