[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
name = "scripting"
version = "0.1.0"

[dependencies.inkwell]
branch = "llvm6-0"
git = "https://github.com/TheDan64/inkwell"
version = "0.1.0"
